package project_euler;

/**
 *

 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */
public class Problem2 {
    public static void main(String[] args) {
        int sum = 2;
        int a = 2;
        int b = 8;

        while(b < 4000000) {
            sum += b;

            int c = nextFibo(a, b);
            a = b;
            b = c;
        }

        System.out.println(sum); // 4613732
    }

    public static int nextFibo(int a, int b) {
        return 4 * b + a;
    }
}
